EXEC = D_recompilte
cc = gcc

default:
	$(CC) -o drecompile D_recompile.c
dynamic:
	$(CC) -Ddynamic -o drecompile D_recompile.c
clean:
	rm -rf D_recompile $(EXEC)
	rm -rf drecompile
	rm -rf D_recompile_test.o
	rm -rf test
	rm -rf test2

